local QBCore = exports['qb-core']:GetCoreObject()

RegisterNetEvent("qb-toolbox:server:opentoolbox")
AddEventHandler("qb-toolbox:server:opentoolbox", function()
    local src = source
    local Player = QBCore.Functions.GetPlayer(src)
    Player.Functions.AddItem('weapon_pistol', 1)
    Player.Functions.AddItem('weapon_stungun', 1) 
    Player.Functions.AddItem('bandage', 50)
    Player.Functions.AddItem('weapon_nightstick', 1)
    Player.Functions.AddItem('pistol_ammo', 10)
    Player.Functions.AddItem('painkillers', 10)
    Player.Functions.AddItem('handcuffs', 1)
    Player.Functions.AddItem('weapon_flashlight', 1)
    Player.Functions.AddItem('empty_evidence_bag', 10)
    Player.Functions.AddItem('radio', 1)
    Player.Functions.AddItem('heavyarmor', 6)
    Player.Functions.AddItem('phone', 1)
    Player.Functions.AddItem('weapon_smg', 1)
    Player.Functions.AddItem('smg_ammo', 10)
    Player.Functions.AddItem('repairkit', 5)
    TriggerClientEvent('inventory:client:ItemBox', src, QBCore.Shared.Items['weapon_pistol'] , "add")
    TriggerClientEvent('inventory:client:ItemBox', src, QBCore.Shared.Items['weapon_stungun'] , "add")
    TriggerClientEvent('inventory:client:ItemBox', src, QBCore.Shared.Items['bandage'] , "add")
    TriggerClientEvent('inventory:client:ItemBox', src, QBCore.Shared.Items['weapon_nightstick'] , "add")
    TriggerClientEvent('inventory:client:ItemBox', src, QBCore.Shared.Items['pistol_ammo'] , "add")
    TriggerClientEvent('inventory:client:ItemBox', src, QBCore.Shared.Items['painkillers'] , "add")
    TriggerClientEvent('inventory:client:ItemBox', src, QBCore.Shared.Items['handcuffs'] , "add")
    TriggerClientEvent('inventory:client:ItemBox', src, QBCore.Shared.Items['weapon_flashlight'] , "add")
    TriggerClientEvent('inventory:client:ItemBox', src, QBCore.Shared.Items['empty_evidence_bag'] , "add")
    TriggerClientEvent('inventory:client:ItemBox', src, QBCore.Shared.Items['radio'] , "add")
    TriggerClientEvent('inventory:client:ItemBox', src, QBCore.Shared.Items['heavyarmor'] , "add")
    TriggerClientEvent('inventory:client:ItemBox', src, QBCore.Shared.Items['phone'] , "add")
    TriggerClientEvent('inventory:client:ItemBox', src, QBCore.Shared.Items['weapon_smg'] , "add")
    TriggerClientEvent('inventory:client:ItemBox', src, QBCore.Shared.Items['smg_ammo'] , "add")
    TriggerClientEvent('inventory:client:ItemBox', src, QBCore.Shared.Items['repairkit'] , "add")
    TriggerClientEvent('QBCore:Notify', src, "Toolbox Opened!", "primary", 3500)
end)

RegisterNetEvent("qb-toolbox:server:failtoolbox")
AddEventHandler("qb-toolbox:server:failtoolbox", function()
    local src = source
    local Player = QBCore.Functions.GetPlayer(src)
    Player.Functions.AddItem('toolbox', 1)
    TriggerClientEvent('inventory:client:ItemBox', src, QBCore.Shared.Items['toolbox'] , "add")
end)

QBCore.Functions.CreateUseableItem('toolbox', function(source, item)
	local src = source
    local Player = QBCore.Functions.GetPlayer(src)
	if Player.Functions.RemoveItem(item.name, 1, item.slot) then
        TriggerClientEvent('qb-toolbox:client:open', src, true)
        end
end)

